import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
/**
 *
 * @author pablo
 */
public class ImgVisor extends javax.swing.JPanel {
    private String ruta;
    private String[] archivos;
    private int pos;
    private final int IMG_WIDTH = 250;
    private final int IMG_HEIGHT = 200;

    /**
     * Creates new form ImgVisor
     */
    public ImgVisor() {
        initComponents();
    }
    
    public void start(){
        pos = 0;
        try{
            iniciar();
        }catch (Exception e){
            System.out.println("RUTA MAL INTRODUCIDA");
            System.out.println(ruta);
        }
    }
    
    private void iniciar(){
        archivos = new File(ruta).list();
        setImage();
    }
    
    private void setImage(){
        ImageIcon img = new ImageIcon(new ImageIcon(ruta  + archivos[pos]).getImage().getScaledInstance(IMG_WIDTH,IMG_HEIGHT, Image.SCALE_FAST));
        jLabel_img.setIcon(img);
    }
 
    public String getRuta() {
        return ruta;
    }

    public void setRuta(String ruta) {
        this.ruta = ruta;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_img = new javax.swing.JLabel();
        jButton_siguiente = new javax.swing.JButton();
        jButton_anterior = new javax.swing.JButton();
        jLabel_rutaimg = new javax.swing.JLabel();

        jButton_siguiente.setText("siguiente");
        jButton_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_siguienteActionPerformed(evt);
            }
        });

        jButton_anterior.setText("anterior");
        jButton_anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_anteriorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_rutaimg, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton_anterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_img, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_siguiente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_anterior, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                    .addComponent(jButton_siguiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_img, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_rutaimg, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_anteriorActionPerformed
            if(pos == 0) {
                pos = archivos.length - 1;
            }else{
                pos--;
            }
            setImage();
    }//GEN-LAST:event_jButton_anteriorActionPerformed

    private void jButton_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_siguienteActionPerformed
        // TODO add your handling code here:
        if(pos == archivos.length - 1) {
                pos = 0 ;
            }else{
                pos++;
            }
        setImage();
    }//GEN-LAST:event_jButton_siguienteActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_anterior;
    private javax.swing.JButton jButton_siguiente;
    private javax.swing.JLabel jLabel_img;
    private javax.swing.JLabel jLabel_rutaimg;
    // End of variables declaration//GEN-END:variables
}
